[build]
  publish = "public"

[functions]
  node_bundler = "esbuild"
  included_files = [
    "layout-positions.json",
    "public/bg_en_rf.jpg",
    "public/bg_en_rf.jpeg",
    "public/bg_en_rf.png",
    "public/seal.png",
    "fonts/*"
  ]
